/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarrantyImport } from './routes/warranty'
import { Route as ReportImport } from './routes/report'
import { Route as DirectReportImport } from './routes/direct-report'
import { Route as DetectionImport } from './routes/detection'
import { Route as CarsImport } from './routes/cars'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WarrantyRoute = WarrantyImport.update({
  path: '/warranty',
  getParentRoute: () => rootRoute,
} as any)

const ReportRoute = ReportImport.update({
  path: '/report',
  getParentRoute: () => rootRoute,
} as any)

const DirectReportRoute = DirectReportImport.update({
  path: '/direct-report',
  getParentRoute: () => rootRoute,
} as any)

const DetectionRoute = DetectionImport.update({
  path: '/detection',
  getParentRoute: () => rootRoute,
} as any)

const CarsRoute = CarsImport.update({
  path: '/cars',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsImport
      parentRoute: typeof rootRoute
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionImport
      parentRoute: typeof rootRoute
    }
    '/direct-report': {
      id: '/direct-report'
      path: '/direct-report'
      fullPath: '/direct-report'
      preLoaderRoute: typeof DirectReportImport
      parentRoute: typeof rootRoute
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportImport
      parentRoute: typeof rootRoute
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/detection': typeof DetectionRoute
  '/direct-report': typeof DirectReportRoute
  '/report': typeof ReportRoute
  '/warranty': typeof WarrantyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/detection': typeof DetectionRoute
  '/direct-report': typeof DirectReportRoute
  '/report': typeof ReportRoute
  '/warranty': typeof WarrantyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cars': typeof CarsRoute
  '/detection': typeof DetectionRoute
  '/direct-report': typeof DirectReportRoute
  '/report': typeof ReportRoute
  '/warranty': typeof WarrantyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/detection'
    | '/direct-report'
    | '/report'
    | '/warranty'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars' | '/detection' | '/direct-report' | '/report' | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/detection'
    | '/direct-report'
    | '/report'
    | '/warranty'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRoute
  DetectionRoute: typeof DetectionRoute
  DirectReportRoute: typeof DirectReportRoute
  ReportRoute: typeof ReportRoute
  WarrantyRoute: typeof WarrantyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRoute,
  DetectionRoute: DetectionRoute,
  DirectReportRoute: DirectReportRoute,
  ReportRoute: ReportRoute,
  WarrantyRoute: WarrantyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cars",
        "/detection",
        "/direct-report",
        "/report",
        "/warranty"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cars": {
      "filePath": "cars.tsx"
    },
    "/detection": {
      "filePath": "detection.tsx"
    },
    "/direct-report": {
      "filePath": "direct-report.tsx"
    },
    "/report": {
      "filePath": "report.tsx"
    },
    "/warranty": {
      "filePath": "warranty.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
